# Use an official Python runtime as a parent image
FROM python:3.6

# Set the working directory to /notebooks
WORKDIR /notebooks

# Copy the current directory contents into the container at /notebooks
ADD . /notebooks


# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make port 8888 available to the world outside this container
EXPOSE 8888

# Define environment variable
ENV NAME World
ENV NAME IPAddress=((ipconfig | findstr [0-9].\.)[0]).Split()[-1]
# start notebook when the container run
CMD ["python -m", "notebook --no-browser --ip=* --NotebookApp.allow_origin=*"]